*&---------------------------------------------------------------------*
*& Include          ZBUK_BELGE_TOP
*&---------------------------------------------------------------------*

TABLES: ekko, ekpo, sscrfields.

CLASS lcl_main DEFINITION DEFERRED.
DATA: gr_main TYPE REF TO lcl_main.


TYPES :BEGIN OF gty_ekko_ekpo,
         ebeln TYPE ekko-ebeln,
         bukrs TYPE ekko-bukrs,
         eadat TYPE ekko-aedat,
         lifnr TYPE ekko-lifnr,
         matnr TYPE ekpo-matnr,
         txz01 TYPE ekpo-txz01,
       END OF gty_ekko_ekpo.

TYPES : BEGIN OF gty_header,
          line TYPE char30,
        END OF gty_header.
DATA: gv_filename TYPE string,
      gt_header   TYPE TABLE OF gty_header,
      gs_header   TYPE gty_header.

DATA: gt_all TYPE TABLE OF gty_ekko_ekpo,
      gs_all TYPE gty_ekko_ekpo.


DATA: go_alv      TYPE REF TO cl_salv_table,
      gx_salv_msg TYPE REF TO cx_salv_msg.

SELECTION-SCREEN BEGIN OF BLOCK b1 WITH FRAME TITLE TEXT-001.
  PARAMETERS: p_ebeln TYPE ekko-ebeln OBLIGATORY.
SELECTION-SCREEN END OF BLOCK b1.

SELECTION-SCREEN BEGIN OF SCREEN 100 AS SUBSCREEN.
  SELECTION-SCREEN BEGIN OF BLOCK b2.
    SELECTION-SCREEN ULINE /10(40).
    SELECTION-SCREEN PUSHBUTTON /10(40) TEXT-003 USER-COMMAND bttn1.
    "alv
    SELECTION-SCREEN ULINE /10(40).
  SELECTION-SCREEN END OF BLOCK b2.
SELECTION-SCREEN END OF SCREEN 100.

SELECTION-SCREEN BEGIN OF SCREEN 200 AS SUBSCREEN.
  SELECTION-SCREEN BEGIN OF BLOCK b3.
    SELECTION-SCREEN ULINE /10(40).
    SELECTION-SCREEN PUSHBUTTON /10(40) TEXT-004 USER-COMMAND bttn2.
    "mail
    SELECTION-SCREEN ULINE /10(40).
  SELECTION-SCREEN END OF BLOCK b3.
SELECTION-SCREEN END OF SCREEN 200.

SELECTION-SCREEN BEGIN OF SCREEN 300 AS SUBSCREEN.
  SELECTION-SCREEN BEGIN OF BLOCK b4.
    SELECTION-SCREEN ULINE /10(40).
    SELECTION-SCREEN PUSHBUTTON /10(40) TEXT-005 USER-COMMAND bttn3.
    PARAMETERS: p_path TYPE string.
    "excel
    SELECTION-SCREEN ULINE /10(40).
  SELECTION-SCREEN END OF BLOCK b4.
SELECTION-SCREEN END OF SCREEN 300.

SELECTION-SCREEN BEGIN OF SCREEN 400 AS SUBSCREEN.
  SELECTION-SCREEN BEGIN OF BLOCK b5.
    SELECTION-SCREEN ULINE /10(40).
    SELECTION-SCREEN PUSHBUTTON /10(40) TEXT-006 USER-COMMAND bttn4.
    PARAMETERS: p_barc TYPE char10 OBLIGATORY.
    "form
    SELECTION-SCREEN ULINE /10(40).
  SELECTION-SCREEN END OF BLOCK b5.
SELECTION-SCREEN END OF SCREEN 400.

SELECTION-SCREEN: BEGIN OF TABBED BLOCK selscrtab FOR 10 LINES,
TAB (20) tab1 USER-COMMAND ucomm1 DEFAULT SCREEN 100,
TAB (20) tab2 USER-COMMAND ucomm2 DEFAULT SCREEN 200,
TAB (20) tab3 USER-COMMAND ucomm3 DEFAULT SCREEN 300,
TAB (20) tab4 USER-COMMAND ucomm4 DEFAULT SCREEN 400,
END OF BLOCK selscrtab.
